= Walkmod Gradle Plugin
Abel Salgado Romero
=======
:version: 0.0.1
:walkmod-url: http://www.walkmod.com/
:issues: https://github.com/abelsromero/gradle-walkmod-plugin/issues
:gradle-url: http://gradle.org/
:maven-gradle-plugin: https://github.com/rpau/maven-walkmod-plugin
:project-name: gradle-walkmod-plugin
:walkmod-cmd: walkmod-cmd:3.0.0
:ivy-url: http://ant.apache.org/ivy/

image:http://img.shields.io/travis/abelsromero/{project-name}/master.svg["Build Status", link="https://travis-ci.org/abelsromero/{project-name}"]
image:http://img.shields.io/coveralls/abelsromero/{project-name}/master.svg["Coverage Status", link="https://coveralls.io/r/abelsromero/{project-name}"]
image:http://img.shields.io/:semver-{version}-blue.svg["Semantic Versioning", link="http://semver.org"]

The {doctitle} is the first tool to provide {walkmod-url}[Walkmod] integration with {gradle-url}[Gradle].
This plugin adds two new tasks to allow checking and applying walkmod changes to your projects.

WARNING: this is a preliminary version and still some work must be done.

== Installation
As long as this is a preliminary version, no fixed repository exists. If you wish to test the tool, you'll need to install it locally from sources.
A `install` task is provided to simplify the installation in maven local.
Use the following snippet inside a Gradle build file:

.build.gradle
[source,groovy]
[subs="attributes"]
----
buildscript {
    repositories {
        mavenLocal()
    }

    dependencies {
        classpath 'org.walkmod:{project-name}:{version}'
    }
}

apply plugin: 'walkmod'
----

== Usage

The plugin adds a two new tasks:

. `walkmodCheck`: checks for possible changes. Same as using `walkmod check` in the command tool.
. `walkmodApply`: applies changes. Same as using `walkmod apply` in the command tool.
. `walkmodPatch`: generates a patch. Same as using `walkmod patch` in the command tool.


=== Properties
Each tasks provides the following properties for its configuration:

[horizontal]
chains:: chain names to check or apply. Type: List<String>. Default: `empty` (all chains).
offline:: `true` to resolve dependencies (uses {ivy-url}[Ivy]), `false` to resolve locally. Type: `boolean`. Default: `false`.
verbose:: `true` to show extra information. Type: `boolean`. Default: `false`.
showErrors:: `true` to get full details when something goes wrong. Type: `boolean`. Default: `true`.
properties:: dynamic parameters for the execution

=== Methods

None right now (this may change in the future).


== Contributing

In the spirit of free and open software, _everyone_ is encouraged to help improve this project.
If you discover errors or omissions in the source code, documentation, please don't hesitate to submit an issue or open a pull request with a fix.
New contributors are always welcome!

Here are some ways *you* can contribute:

* by using prerelease (alpha, beta or preview) versions
* by reporting bugs
* by suggesting new features
* by writing or editing documentation
* by writing specifications
* by writing code -- _No patch is too small._
** fix typos
** add comments
** clean up inconsistent whitespace
** write tests!
* by refactoring code
* by fixing {uri-issues}[issues]
* by reviewing patches

== Special thanks

* To the {walkmod-url}[Walkmod] team for such a tool.
* To @aalmiray's {asciidoctor-gradle-plugin-url}[asciidoctor-gradle-plugin] which served as foundation for this one.
